### ISSUE TITLE
Validator plugins that experience exceptions should not prevent the remaining validator plugins from executing normally

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#341]
Validator plugins that experience exceptions should not prevent the remaining validator plugins from executing normally.

## References:
Definition validation function: https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/validate/_validate.py#L136-L150

Primitive validation function: https://github.com/jondavid-black/AaC/blob/3dfc11baf0ec8d7250608bd16caebdae837fc8af/python/src/aac/validate/_validate.py#L193-L206

## AC:
- [ ] Validator plugins are executed with error-handling that doesn't prevent the execution of other validation plugins if one of them raises an exception.
- [ ] Definition validation has a try/except error handler implemented. 
  - [ ] The exception is logged
  - [ ] The exception is returned to the user as an error message
- [ ] Exceptions that occur during validation are treated as if they were errors reported by the plugins
  - [ ] Definition validation
  - [ ] Primitive validation
- [ ] There is a test that demonstrates a validation plugin throwing a runtime exception, but not preventing results from other validation plugins.

**Comment by cvchaparro** [comment]
Per our discussion during planning, I think we would want to patch this function so that we can insert the test plugin that throws the runtime exception followed by a single validator plugin that is expected to fail. Then we can assert the error messages are listed in the `PluginExecutionResult` in the expected order.

https://github.com/jondavid-black/AaC/blob/467853bae55b11fa58a2477f6a108cbe29dd94d6/python/src/aac/lang/language_context.py#L525-L535
