### ISSUE TITLE
Install AaC across air gap

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#398]
I want to be able to install AaC on my local PC which may be disconnected from the internet or behind a firewall/proxy that I do not control.

AC:

- [ ] Must publish an installation package with AaC and all dependencies
- [ ] Must be able to download the installation package
- [ ] Must be able to check the installation package against a hash to ensure validity
- [ ] Must be able to successfully install AaC (and dependencies if necessary) from the installation package without accessing network resources

**Comment by jondavid-black** [comment]
Here's a [Q&A](https://superuser.com/questions/1523218/how-to-install-python-packages-with-all-dependencies-offline-via-pip3) that may be useful.

**Comment by Coffee2Bits** [comment]
I was able to get a prototype working for this. Pip has a command that will fetch the wheels of your runtime dependencies `pip wheel ./` and place them in the directory next to the setup.py file. 

After moving the dependencies into a clean environment, I was able to install the aac wheel with the `--no-index` pip argument.
```
pip install aac-0.1.2-py3-none-any.whl --no-index --find-links ./
```

I did have trouble installing aac from a tar.gz archive, but if the wheels are all uncompressed it installed AaC without hitting pypi.

**Comment by jondavid-black** [comment]
Based on this, I'd say the answer is to create a pipeline that fetches the wheels, zips them up (including aac), and publishes them as an artifact in GitHub.  This should be executed when we publish releases to pypi.  We'd also need a little bit of documentation added to capture the offline installation steps/commands.

What is it about hash-verification that would push things to a plug-in rather than just a GitHub action solution?

**Comment by Coffee2Bits** [comment]
During my first investigation pass there were some complicating issues such as pip not having any native support for generating a list of the requirements with their hashes -- it only supports generating hashes for individual packages. The other complicating factor is that pip needs a `setup.py` or `pyproject.toml` to install with, but our project's setup.py would need to be drastically altered to support installing in an air-gapped environment. 

The complexity of multiple steps and some items likely needing to be templated lead me to the option of producing a plugin.

That being said, on a second investigation I was able to find [pip-tools](https://github.com/jazzband/pip-tools), which will produce a requirements list with hashes from our setup. With `pip-tools` I can create the entire package installer purely from the command-line; a process simple enough for a pipeline stage.

The steps are pretty easy. Assuming that you're in the python directory:
```
pip wheel ./
mv *.whl air_gap_installer_directory
pip-compile --generate-hashes setup.py
mv requirements.txt air_gap_installer_directory
cd air_gap_installer_directory
tar -cvf aac_offline_install.tar.gz .
```

I agree that we'll need some additional documentation on how to use the installer. I think it would be beneficial for us to get the Github releases going so that we can host the offline package installer with the relevant AaC release version.
