### ISSUE TITLE
I want the LSP to support Folding Ranges

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#461]
As an AaC user, I want the LSP to support Folding Ranges, so that I can condense and organize my AaC file in the IDE.

## References:
LSP Specification for the feature: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_foldingRange

Pygls `FoldingRange` class: https://github.com/openlawlibrary/pygls/blob/b84098cc05426877ba62dce75aeec2ba4fa45056/pygls/lsp/types/language_features/folding_range.py#L42-L67

## AC:
- [x] There is a new LSP provider `FoldingRangeProvider`
- [x] For every definition, a folding range is provided for:
  - [x] The root key to the end of the definition
  - [x] For each top-level field and sub-field in a definition
- [x] Each folding range must specify:
  - [x] a starting line
  - [x] an ending line
  - [ ] The folding 'kind'
    - [ ] For `imports` the region kind is specified as `import`
    - [x] For all other folding regions, they are specified as `region`

**Comment by cvchaparro** [comment]
I’ve got basic definition folding pretty much working but handling imports and top-level fields is proving to be a bit tricky.

Specifically, regarding imports, it seems to be the case that I'll need to modify the `parse` function so that we get lexeme information for imports. Of course, this may cause validation issues because we don't keep the `imports` list attached to the definition.

Finding the last line of each top-level field is also not straightforward but I'm working on that, too.
