### ISSUE TITLE
YAML Parsing errors should be handled gracefully

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#587]
YAML Parsing errors should be handled gracefully instead of returning python log traces.

## AC:
- [x] Failure to parse a YAML string should be handled gracefully
  - [x] A massaged error is returned to the user indicating what the cause of the YAML parsing error is.
  - [x] The error and trace are logged as an error level message

**Comment by lizzcondrey** [comment]
This will have to persist to next sprint because it was determined in discussions with the team that the avenue I went down exposed a different and larger problem than what this card was originally addressing. So to finish addressing the problem we will carry this forward. Need to probably make a second card to address the original problem of this card for a non-plugin yaml file trying to be evaluated.
