### ISSUE TITLE
Generate Gherkin from Behavior Scenarios

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#8]
As a developer I want Gherkin feature files automatically generated from the model so that I do not have to recreate the behavior specification by hand.

AC:
- [ ] Generate model behavior acceptance entries into Gherkin feature files.
- [ ] Each acceptance scenario should be generated into its own feature file.

**Comment by Coffee2Bits** [comment]
Due to the [requirement in Gherkin ](https://cucumber.io/docs/gherkin/reference/#keywords) that each feature file starts with the `feature` keyword, AC # 2 is in conflict with the language requirements and should instead be, "Each behavior entry should be generated into its own feature file."

So, each behavior entry will map to a Gherkin feature file, and the scenarios in the behavior entry will be generated as scenarios in the feature file, like the reference gherkin feature file provided in the docs and seen below.
```gherkin
Feature: Guess the word

  # The first example has two steps
  Scenario: Maker starts a game
    When the Maker starts a game
    Then the Maker waits for a Breaker to join

  # The second example has three steps
  Scenario: Breaker joins a game
    Given the Maker has started a game with the word "silky"
    When the Breaker joins the Maker's game
    Then the Breaker must guess a word with 5 characters
```
