### ISSUE TITLE
Move AaC Core Spec functionality to a core spec module

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#93]
Move AaC Core Spec functionality to a core spec module, from the util module.

AC:
- [ ] Create a new module for supplying core spec information
  - [ ] New directory in `src/aac`
  - [ ] Implements `__init__.py` to register the directory as a python module
  - [ ] New module methods are exposed via `__init__.py`
- [ ] The new module should include the following functions from util.py. Function names can be altered for improved readability.
   - [ ] `get_aac_spec`
   - [ ] `get_aac_spec_as_yaml`
   - [ ] `get_primitives`
   - [ ] `get_roots`
- [ ] Any global state with these functions is moved to the new module
- [ ] The core AaC yaml file is loaded via the package resource loader
- [ ] Remove `extend_aac_spec` since its functionality is now in the validator module

**Comment by Coffee2Bits** [comment]
Additional context can be found in the duplicated issue #109

**Comment by cvchaparro** [comment]
@Coffee2Bits

These are the AC from #109 that weren't transferred but I think are still needed:

- [ ] The AaC `setup.py` is set to include the yaml file. 
  - [ ] `setup.py:setup()` includes this line `package_data={'aac.model': ['AaC.yaml']}`
- [ ] Update `util.py` to use `importlib.resources.path` to load the `AaC.yaml` file.
- [ ] The pipeline exercises the distribution wheel
   - [ ] `validate` works
   - [ ] `aac-core-spec` works

Since you wrote these stories, can you confirm if they are needed, or not?
