### ISSUE TITLE
Cannot Validate when Extension is done to root

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#95]
As a plugin developer I want to extend root so that I can create a new base structure in AaC YAML.

This is a bug currently blocking #30 .

The issue appears to be in the validator.  When getting the list of root types to support validation it only pulls core AaC root types and does not consider extensions.

**Comment by Coffee2Bits** [comment]
I found the issue, the validator is retrieving root specs from the util.py function `get_roots()` which uses an unextended model of the core AaC spec.

https://github.com/jondavid-black/AaC/blob/7d2e75332388d2299ab218a578389dcd9a5981f6/src/aac/validator.py#L90-L97

To fix this issue we'll need to provide root types from the validator's `VALIDATOR_CONTEXT` since that is where the extended models are kept. I've got a fix in place, but it's causing an impact to some of the tests that I'm working through.
