### ISSUE TITLE
Allow Plugin with Extension Only

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#99]
As a plugin developer I want to generate a plugin with no command so that I can extend the data model for my team.

AC:

- [x] Behavior must be optional when defining a model
- [x] Generate plugin must work when the model has no defined behavior
- [x] Installing the generated plugin must extend the data model as specified

**Comment by Coffee2Bits** [comment]
I don't think we can generate a plugin without it defining a `model` since that's how we source basic information like the plugin's name. I think the simplified model https://github.com/jondavid-black/AaC/issues/87 story will help lower the burden of defining a model, but we'll always need a model to generate a plugin.

**Comment by jondavid-black** [comment]
I agree with your recommendation and updated the AC accordingly.
